## Centalizando as bases

Notebook utilizado para centralizar todas as variáveis de interesse em único arquivo .csv

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install unidecode

import pandas as pd
import unidecode

Collecting unidecode
  Downloading https://files.pythonhosted.org/packages/9e/25/723487ca2a52ebcee88a34d7d1f5a4b80b793f179ee0f62d5371938dfa01/Unidecode-1.2.0-py2.py3-none-any.whl (241kB)
     |████████████████████████████████| 245kB 7.5MB/s
Installing collected packages: unidecode
Successfully installed unidecode-1.2.0

In [7]:
main_dataset_path = '/content/drive/MyDrive/mo286/MO826 - projeto_final/datasets/principais_(atualizado_2021-05-13)/raw/covid.saude.gov.br/INFLUD-05-04-2021.csv'
ocupacao_leito_path = '/content/drive/MyDrive/mo286/MO826 - projeto_final/datasets/principais_(atualizado_2021-05-13)/raw/OpenDataSUS/esus-vepi.LeitoOcupacao_28_04_2021.csv'
medicos_enfermeiros_path = '/content/drive/MyDrive/mo286/MO826 - projeto_final/datasets/principais_(atualizado_2021-05-13)/raw/IBGE/agencia_ibge_noticias_.xlsx'
trabalhadores_informais_path = '/content/drive/MyDrive/mo286/MO826 - projeto_final/datasets/principais_(atualizado_2021-05-13)/raw/IBGE/ibge_trabalhadores informais.xlsx'

In [4]:
# Função para remover a acentuação
def remove_accentuation(df):
    return df.apply(lambda item: unidecode.unidecode(item))

# Função para deixar os termos em letra maiúscula 
def to_uppercase(df):
    return df.apply(lambda item: item.strip().upper())

# Função para traduzir o formato de data para o mesmo da base principal
def translate_date(date):
    x = pd.to_datetime(date)
    try:
        new_date = "{:02d}/{:02d}/{:04d}".format(int(x.day), int(x.month), int(x.year))
    except:
        new_date = None
    return new_date
  
uf_dict = {
    'ACRE': 'AC',
    'ALAGOAS': 'AL',
    'AMAPA': 'AP',
    'AMAZONAS': 'AM',
    'BAHIA': 'BA',
    'CEARA': 'CE',
    'DISTRITO FEDERAL': 'DF',
    'ESPIRITO SANTO': 'ES',
    'GOIAS': 'GO',
    'MARANHAO': 'MA',
    'MATO GROSSO': 'MT',
    'MATO GROSSO DO SUL': 'MS',
    'MINAS GERAIS': 'MG',
    'PARA': 'PA',
    'PARAIBA': 'PB',
    'PARANA':'PR',
    'PERNAMBUCO': 'PE',
    'PIAUI': 'PI',
    'RIO DE JANEIRO': 'RJ',
    'RIO GRANDE DO NORTE': 'RN',
    'RIO GRANDE DO SUL': 'RS',
    'RONDONIA': 'RO',
    'RORAIMA': 'RR',
    'SANTA CATARINA': 'SC',
    'SAO PAULO': 'SP',
    'SERGIPE': 'SE',
    'TOCANTINS': 'TO'
}

def translate_uf(df):
  return df.apply(lambda x: uf_dict[x])

In [5]:
# covid_saude_gov
df_main = pd.read_csv(main_dataset_path, sep=';')
df_main.head(10)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (15,18,60,62,63,64,92,94,106,108,115,117,118,119,123) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

   DT_NOTIFIC  SEM_NOT  DT_SIN_PRI  SEM_PRI  ... DT_RES RES_IGG  RES_IGM RES_IGA
0  14/01/2020        3  07/01/2020        2  ...    NaN     NaN      NaN     NaN
1  28/01/2020        5  27/01/2020        5  ...    NaN     NaN      NaN     NaN
2  17/02/2020        8  04/02/2020        6  ...    NaN     NaN      NaN     NaN
3  27/01/2020        5  21/01/2020        4  ...    NaN     NaN      NaN     NaN
4  10/03/2020       11  05/03/2020       10  ...    NaN     NaN      NaN     NaN
5  03/03/2020       10  29/02/2020        9  ...    NaN     NaN      NaN     NaN
6  23/03/2020       13  21/03/2020       12  ...    NaN     NaN      NaN     NaN
7  24/03/2020       13  12/03/2020       11  ...    NaN     NaN      NaN     NaN
8  14/03/2020       11  12/03/2020       11  ...    NaN     NaN      NaN     NaN
9  23/03/2020       13  15/03/2020       12  ...    NaN     NaN      NaN     NaN

[10 rows x 154 columns]

In [8]:
# Bases Agencia IBGE
df_agencia_ibge_leitos = pd.read_excel(medicos_enfermeiros_path, sheet_name = 'Leitos_de_UTI')
df_agencia_ibge_respiradores = pd.read_excel(medicos_enfermeiros_path, sheet_name = 'Respiradores_por_municípios')
df_agencia_ibge_medicos = pd.read_excel(medicos_enfermeiros_path, sheet_name = 'Medicos_por_municípios')
df_agencia_ibge_enfermeiros = pd.read_excel(medicos_enfermeiros_path, sheet_name = 'Enfermeiros_municípios')

## Dados de leitos

In [9]:
df_agencia_ibge_leitos['ID_MN_RESI'] = remove_accentuation(df_agencia_ibge_leitos['Município'])
df_agencia_ibge_leitos['ID_MN_RESI'] = to_uppercase(df_agencia_ibge_leitos['ID_MN_RESI'])
df_agencia_ibge_leitos['SG_UF'] = remove_accentuation(df_agencia_ibge_leitos['Estado ou Distrito Federal'])
df_agencia_ibge_leitos['SG_UF'] = to_uppercase(df_agencia_ibge_leitos['SG_UF'])
df_agencia_ibge_leitos['SG_UF'] = translate_uf(df_agencia_ibge_leitos['SG_UF'])
df_agencia_ibge_leitos.head(2)

        Município Estado ou Distrito Federal  ...      ID_MN_RESI  SG_UF
0       São Paulo                  São Paulo  ...       SAO PAULO     SP
1  Rio de Janeiro             Rio de Janeiro  ...  RIO DE JANEIRO     RJ

[2 rows x 10 columns]

## Dados de respiradores

In [10]:
df_agencia_ibge_respiradores['ID_MN_RESI'] = remove_accentuation(df_agencia_ibge_respiradores['Município'])
df_agencia_ibge_respiradores['ID_MN_RESI'] = to_uppercase(df_agencia_ibge_respiradores['ID_MN_RESI'])
df_agencia_ibge_respiradores['SG_UF'] = remove_accentuation(df_agencia_ibge_respiradores['Estado ou Distrito Federal'])
df_agencia_ibge_respiradores['SG_UF'] = to_uppercase(df_agencia_ibge_respiradores['SG_UF'])
df_agencia_ibge_respiradores['SG_UF'] = translate_uf(df_agencia_ibge_respiradores['SG_UF'])
df_agencia_ibge_respiradores.head(2)

        Município Estado ou Distrito Federal  ...      ID_MN_RESI  SG_UF
0       São Paulo                  São Paulo  ...       SAO PAULO     SP
1  Rio de Janeiro             Rio de Janeiro  ...  RIO DE JANEIRO     RJ

[2 rows x 10 columns]

## Dados de médicos

In [11]:
df_agencia_ibge_medicos['ID_MN_RESI'] = remove_accentuation(df_agencia_ibge_medicos['Município'])
df_agencia_ibge_medicos['ID_MN_RESI'] = to_uppercase(df_agencia_ibge_medicos['ID_MN_RESI'])
df_agencia_ibge_medicos['SG_UF'] = remove_accentuation(df_agencia_ibge_medicos['Estado'])
df_agencia_ibge_medicos['SG_UF'] = to_uppercase(df_agencia_ibge_medicos['SG_UF'])
df_agencia_ibge_medicos['SG_UF'] = translate_uf(df_agencia_ibge_medicos['SG_UF'])
df_agencia_ibge_medicos.head(2)

        Município          Estado  ...      ID_MN_RESI  SG_UF
0       São Paulo       São Paulo  ...       SAO PAULO     SP
1  Rio de Janeiro  Rio de Janeiro  ...  RIO DE JANEIRO     RJ

[2 rows x 10 columns]

## Dados de enfermeiros

In [12]:
df_agencia_ibge_enfermeiros['ID_MN_RESI'] = remove_accentuation(df_agencia_ibge_enfermeiros['Município'])
df_agencia_ibge_enfermeiros['ID_MN_RESI'] = to_uppercase(df_agencia_ibge_enfermeiros['ID_MN_RESI'])
df_agencia_ibge_enfermeiros['SG_UF'] = remove_accentuation(df_agencia_ibge_enfermeiros['Estado ou Distrito Federal'])
df_agencia_ibge_enfermeiros['SG_UF'] = to_uppercase(df_agencia_ibge_enfermeiros['SG_UF'])
df_agencia_ibge_enfermeiros['SG_UF'] = translate_uf(df_agencia_ibge_enfermeiros['SG_UF'])
df_agencia_ibge_enfermeiros.head(2)

        Município Estado ou Distrito Federal  ...      ID_MN_RESI  SG_UF
0       São Paulo                  São Paulo  ...       SAO PAULO     SP
1  Rio de Janeiro             Rio de Janeiro  ...  RIO DE JANEIRO     RJ

[2 rows x 10 columns]

## Dados leitos e ocupação

In [13]:
# DataSUS ocupacao leito e ocupacao
df_leito_ocupacao = pd.read_csv(ocupacao_leito_path, sep=',')
df_leito_ocupacao['ID_MN_RESI'] = remove_accentuation(df_leito_ocupacao['municipioNotificacao'])
df_leito_ocupacao['ID_MN_RESI'] = to_uppercase(df_leito_ocupacao['ID_MN_RESI'])
df_leito_ocupacao['SG_UF'] = remove_accentuation(df_leito_ocupacao['estadoNotificacao'])
df_leito_ocupacao['SG_UF'] = to_uppercase(df_leito_ocupacao['SG_UF'])
df_leito_ocupacao['SG_UF'] = translate_uf(df_leito_ocupacao['SG_UF'])
df_leito_ocupacao['DT_NOTIFIC'] = df_leito_ocupacao['dataNotificacao'].apply(lambda x: translate_date(x))
df_leito_ocupacao.head(2)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

          _id           dataNotificacao  ... SG_UF  DT_NOTIFIC
0  p5Ez41Zu6B  2020-04-14T03:00:00.000Z  ...    SC  14/04/2020
1  eUOMsSt7T7  2020-04-15T03:00:00.000Z  ...    RJ  15/04/2020

[2 rows x 24 columns]

## Dados Trabalhadores Informais

In [14]:
df_ibge_trabalhadores_informais = pd.read_excel(trabalhadores_informais_path, sheet_name = 'trabalhadores_informais_for_mer')
df_ibge_trabalhadores_informais['SG_UF'] = remove_accentuation(df_ibge_trabalhadores_informais['UF'])
df_ibge_trabalhadores_informais['SG_UF'] = to_uppercase(df_ibge_trabalhadores_informais['SG_UF'])
df_ibge_trabalhadores_informais['SG_UF'] = translate_uf(df_ibge_trabalhadores_informais['SG_UF'])
df_ibge_trabalhadores_informais.head(27)

                     UF  ...  SG_UF
0              Rondônia  ...     RO
1                  Acre  ...     AC
2              Amazonas  ...     AM
3               Roraima  ...     RR
4                  Pará  ...     PA
5                 Amapá  ...     AP
6             Tocantins  ...     TO
7              Maranhão  ...     MA
8                 Piauí  ...     PI
9                 Ceará  ...     CE
10  Rio Grande do Norte  ...     RN
11              Paraíba  ...     PB
12           Pernambuco  ...     PE
13              Alagoas  ...     AL
14              Sergipe  ...     SE
15                Bahia  ...     BA
16         Minas Gerais  ...     MG
17       Espirito Santo  ...     ES
18       Rio de Janeiro  ...     RJ
19            São Paulo  ...     SP
20               Paraná  ...     PR
21       Santa Catarina  ...     SC
22    Rio Grande do Sul  ...     RS
23   Mato Grosso do Sul  ...     MS
24          Mato Grosso  ...     MT
25                Goiás  ...     GO
26     Distrito Federal  ...     DF

[27 rows x 6 columns]


## Centralizando os dados

### Gerando versao apenas com informações relevantes de todos os datasets

In [15]:
df_leito_ocupacao_merge = df_leito_ocupacao[
    ['ID_MN_RESI',
     'SG_UF',
     'DT_NOTIFIC',
     'ocupacaoSuspeitoCli',
     'ocupacaoSuspeitoUti',
     'ocupacaoConfirmadoCli',
     'ocupacaoConfirmadoUti',
     'saidaSuspeitaObitos',
     'saidaSuspeitaAltas',
     'saidaConfirmadaObitos',
     'saidaConfirmadaAltas']]

df_agencia_ibge_enfermeiros_merge = df_agencia_ibge_enfermeiros[
    ['ID_MN_RESI',
     'SG_UF',
     'População Estimada (2019)',
     'Total de Enfermeiros',
     'Enfermeiros do SUS',
     'Enfermeiros a cada 100 mil habitantes',
     'Enfermeiros do SUS a cada 100 mil habitantes']]

df_agencia_ibge_medicos_merge = df_agencia_ibge_medicos[
    ['ID_MN_RESI',
     'SG_UF',
     'Total de médicos',
     'Médicos do SUS',
     'Médicos a cada 100 mil habitantes',
     'Médicos do SUS a cada 100 mil habitantes']]

df_agencia_ibge_respiradores_merge = df_agencia_ibge_respiradores[
    ['ID_MN_RESI',
     'SG_UF',
     'Total de Respiradores',
     'Respiradores a cada 100 mil habitantes',
     'Respiradores do SUS a cada 100 mil habitantes',
     'Total de Respiradores do SUS']]

df_agencia_ibge_leitos_merge = df_agencia_ibge_leitos[
    ['ID_MN_RESI',
     'SG_UF',
     'Total de Leitos de UTI',
     'Leitos de UTI a cada 100 mil habitantes',
     'Leitos de UTI do SUS',
     'Leitos do SUS a cada 100 mil habitantes']]
    
df_ibge_trabalhadores_informais_merge = df_ibge_trabalhadores_informais[
    ['SG_UF',
     'Trabalhadores informais na unidade da Federação (julho 2019)',
     'Trabalhadores informais nas Regiões Metropolitas (julho 2019)',
     'Trabalhadores informais Capital (julho 2019)',
     'Trabalhadores informais no Interior (julho 2019)'
    ]
]

### Fazendo merge dos datasets entre si antes do merge com o principal

In [16]:
df_merged_ibge = df_agencia_ibge_enfermeiros_merge.merge(df_agencia_ibge_medicos_merge, on =['ID_MN_RESI', 'SG_UF'], how='left')
df_merged_ibge = df_merged_ibge.merge(df_agencia_ibge_respiradores_merge, on =['ID_MN_RESI', 'SG_UF'], how='left')
df_merged_ibge = df_merged_ibge.merge(df_agencia_ibge_leitos_merge, on =['ID_MN_RESI', 'SG_UF'], how='left')
df_merged_ibge = df_merged_ibge.merge(df_ibge_trabalhadores_informais_merge, on =['SG_UF'], how='left')
df_merged = df_leito_ocupacao_merge.merge(df_merged_ibge, on = ["ID_MN_RESI", "SG_UF"], how = 'left')
df_merged.head(27)

        ID_MN_RESI  ... Trabalhadores informais no Interior (julho 2019)
0          ITAPEMA  ...                                      199875.6738
1   RIO DE JANEIRO  ...                                      117416.9413
2          NITEROI  ...                                      117416.9413
3    VARZEA ALEGRE  ...                                       46116.6661
4        ENCANTADO  ...                                      262278.8602
5        ENCANTADO  ...                                      262278.8602
6        ENCANTADO  ...                                      262278.8602
7      FARROUPILHA  ...                                      262278.8602
8        ENCANTADO  ...                                      262278.8602
9    VARZEA ALEGRE  ...                                       46116.6661
10       ENCANTADO  ...                                      262278.8602
11   VARZEA ALEGRE  ...                                       46116.6661
12   VARZEA ALEGRE  ...                                       46116.6661
13       ENCANTADO  ...                                      262278.8602
14   VARZEA ALEGRE  ...                                       46116.6661
15   VARZEA ALEGRE  ...                                       46116.6661
16   VARZEA ALEGRE  ...                                       46116.6661
17     FARROUPILHA  ...                                      262278.8602
18   VARZEA ALEGRE  ...                                       46116.6661
19   VARZEA ALEGRE  ...                                       46116.6661
20       ENCANTADO  ...                                      262278.8602
21     FARROUPILHA  ...                                      262278.8602
22     FARROUPILHA  ...                                      262278.8602
23         LAJEADO  ...                                      262278.8602
24     FARROUPILHA  ...                                      262278.8602
25         LAJEADO  ...                                      262278.8602
26         LAJEADO  ...                                      262278.8602

[27 rows x 32 columns]

### Salvando em arquivo csv

In [ ]:
df_merged.to_csv("/content/drive/MyDrive/Colab Notebooks/merged_datasets_datasus_ibgenoticias_v5.csv", index=False)